export const ADD_LABEL="ADD_LABEL"
export const DELETE_LABEL="DELETE_LABEL"
export const UPDATE_LABEL="UPDATE_LABEL"
export const GET_LABEL="GET_LABEL"



export const GET_ALL_NOTES="GET_ALL_LABELS"
export const FETCH_USERS_REQUESTS="GET_USERS_REQUESTS"
export const FETCH_USER_FAILURE="FETCH_USER_FAILURE"
export const ADDLABEL="ADDLABEL"
export const GET_ALL_THE_LABELS="GET_ALL_THE_LABELS"
export const ONLY_LABELS_LIST="ONLY_LABELS_LIST"
export const GET_USER_ID="GET_USER_ID"
export const SET_EMAIL_ID="SET_EMAIL_ID"
export const UPDATE_LABEL_ID="UPDATE_LABEL_ID"
export const UPDATE_LABEL_ID_INSTATE="UPDATE_LABEL_ID_INSTATE"

